# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 12:21
from __future__ import unicode_literals

import builtins
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosarica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_K', models.CharField(max_length=50)),
                ('cena_K', models.IntegerField()),
                ('kolicina_K', models.IntegerField()),
                ('stevilo_K', models.IntegerField()),
                ('opis_K', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Narocilo_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_K_N', models.IntegerField()),
                ('stevilo_K_N', models.IntegerField()),
                ('datum_K_N', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('datum_K_N_obdelano', models.DateTimeField(blank=True, default=None)),
                ('pogostost_dostave_K', models.CharField(max_length=40)),
                ('obdelano_N_K', models.BooleanField(default=False)),
                ('kosarica_K', models.ForeignKey(on_delete=builtins.id, to='KmetApp.Kosarica')),
            ],
        ),
        migrations.CreateModel(
            name='Narocilo_O',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_N_O', models.IntegerField()),
                ('kolicina_N_O', models.IntegerField()),
                ('obdelano_N_O', models.BooleanField(default=False)),
                ('datum_N_O', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('datum_N_O_obdelano', models.DateTimeField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Novica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov_Novica', models.CharField(max_length=100)),
                ('opis_Novica', models.CharField(max_length=50000)),
                ('datum_objave', models.DateTimeField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_O', models.CharField(max_length=50)),
                ('cena_O', models.IntegerField()),
                ('kolicina_O', models.IntegerField()),
                ('opis_O', models.CharField(max_length=200)),
                ('datum_O', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('aktiven_O', models.BooleanField(default=True)),
                ('slika', models.CharField(max_length=100)),
                ('pic', models.ImageField(default='img/Oglas/default.jpg', upload_to='img/Oglas/')),
            ],
        ),
        migrations.CreateModel(
            name='Priloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.BinaryField()),
                ('novica_id', models.ForeignKey(on_delete=builtins.id, to='KmetApp.Novica')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('ime', models.CharField(max_length=100)),
                ('priimek', models.CharField(max_length=100)),
                ('naslov', models.CharField(max_length=50)),
                ('postna_st', models.IntegerField()),
                ('kraj', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='oglas',
            name='prodajalec_O',
            field=models.ForeignKey(on_delete=builtins.id, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='narocilo_o',
            name='kupec_O',
            field=models.ForeignKey(on_delete=builtins.id, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='narocilo_o',
            name='oglas_O',
            field=models.ForeignKey(on_delete=builtins.id, to='KmetApp.Oglas'),
        ),
        migrations.AddField(
            model_name='narocilo_k',
            name='kupec_K',
            field=models.ForeignKey(on_delete=builtins.id, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kosarica',
            name='prodajalec_K',
            field=models.ForeignKey(on_delete=builtins.id, to=settings.AUTH_USER_MODEL),
        ),
    ]
