# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0002_auto_20161027_1424'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='oglas',
            name='slika',
            field=models.FileField(default='img/Oglas/default.jpg', upload_to='img/Oglas/'),
        ),
    ]
