# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0003_auto_20161031_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='mesto_pridelave',
            field=models.CharField(default='', max_length=50),
        ),
    ]
