# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-07-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0003_oglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='opis_O',
            field=models.CharField(max_length=200),
        ),
    ]
