# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0004_auto_20161108_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosarica',
            name='aktiven_O',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kosarica',
            name='datum_O',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='kosarica',
            name='mesto_pridelave',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kosarica',
            name='slika',
            field=models.FileField(default='img/Oglas/default.jpg', upload_to='img/Oglas/'),
        ),
    ]
