# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-07-26 18:09
from __future__ import unicode_literals

import builtins
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0005_oglas_datum_o'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narocilo_O',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_N_O', models.IntegerField()),
                ('kolicina_N_O', models.IntegerField()),
                ('obdelano_N_O', models.BooleanField(default=False)),
                ('datum_N_O', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('kupec_O', models.ForeignKey(on_delete=builtins.id, to=settings.AUTH_USER_MODEL)),
                ('oglas_O', models.ForeignKey(on_delete=builtins.id, to='KmetApp.Oglas')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
