# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0005_auto_20161208_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kosarica',
            old_name='aktiven_O',
            new_name='aktiven_K',
        ),
        migrations.RenameField(
            model_name='kosarica',
            old_name='datum_O',
            new_name='datum_K',
        ),
       
    ]
