# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-06 14:09
from __future__ import unicode_literals

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0007_auto_20160805_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosarica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_K', models.CharField(max_length=50)),
                ('cena_K', models.IntegerField()),
                ('kolicina_K', models.IntegerField()),
                ('stevilo_K', models.IntegerField()),
                ('opis_K', models.CharField(max_length=200)),
                ('prodajalec_K', models.ForeignKey(on_delete=builtins.id, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
