# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0007_auto_20170119_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oglas',
            name='pic',
        ),
    ]
