# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-07 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0008_kosarica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narocilo_K',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_K_N', models.IntegerField()),
                ('stevilo_K_N', models.IntegerField()),
                ('datum_K_N', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('datum_K_N_obdelano', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pogostost_dostave_K', models.CharField(max_length=40)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
