# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-07 19:13
from __future__ import unicode_literals

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0009_narocilo_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='narocilo_k',
            name='kupec_K',
            field=models.ForeignKey(default='', on_delete=builtins.id, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='narocilo_k',
            name='oglas_K',
            field=models.ForeignKey(default='', on_delete=builtins.id, to='KmetApp.Oglas'),
        ),
    ]
