# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-07 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0010_auto_20160807_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narocilo_k',
            old_name='oglas_K',
            new_name='kosarica_K',
        ),
    ]
