# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-08 03:19
from __future__ import unicode_literals

import builtins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0012_narocilo_k_obdelano_n_k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narocilo_k',
            name='kosarica_K',
            field=models.ForeignKey(on_delete=builtins.id, to='KmetApp.Oglas'),
        ),
        migrations.AlterField(
            model_name='narocilo_k',
            name='kupec_K',
            field=models.ForeignKey(on_delete=builtins.id, to=settings.AUTH_USER_MODEL),
        ),
    ]
