# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-08 15:05
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0013_auto_20160808_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narocilo_k',
            name='datum_K_N_obdelano',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='narocilo_k',
            name='kosarica_K',
            field=models.ForeignKey(on_delete=builtins.id, to='KmetApp.Kosarica'),
        ),
        migrations.AlterField(
            model_name='narocilo_o',
            name='datum_N_O_obdelano',
            field=models.DateTimeField(blank=True),
        ),
    ]
