# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-08 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0014_auto_20160808_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narocilo_k',
            name='datum_K_N_obdelano',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='narocilo_o',
            name='datum_N_O_obdelano',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
