# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-08-12 15:15
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KmetApp', '0015_auto_20160808_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov_Novica', models.CharField(max_length=100)),
                ('opis_Novica', models.CharField(max_length=50000)),
                ('datum_objave', models.DateTimeField(blank=True, default=None)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Priloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.BinaryField()),
                ('novica_id', models.ForeignKey(on_delete=builtins.id, to='KmetApp.Novica')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
